
import pandas as pd
import matplotlib.pyplot as plt
from time import perf_counter

# make plots
start_time = perf_counter()

showAngle = pd.read_csv('showAngle.csv')
showTSRC = pd.read_csv('showTSRC.csv')

try:
    showAngle['Time'] = pd.to_datetime(showAngle['Time'], format='%Y-%m-%d %H:%M:%S.%f')
except Exception as e:
    print(f"Error parsing showAngle['Time']: {e}")

try:
    showTSRC['T_mid'] = pd.to_datetime(showTSRC['T_mid'], format='%Y-%m-%d %H:%M:%S.%f')
except Exception as e:
    print(f"Error parsing showTSRC['T_mid']: {e}")
end_time = perf_counter()
print(f"csv read complete take {end_time - start_time}")

start_time = perf_counter()

plt.figure(figsize=(30, 15))
plt.plot(showAngle['Time'], showAngle['AZ'], label='Azimuth', color='blue', linestyle='-')
plt.xlabel('Time')
plt.ylabel('Angle (degrees)')
plt.title('AZ over Time')
plt.grid()
plt.legend()
plt.xticks(rotation=30)
plt.savefig('Plots/AZ_over_Time.png',dpi = 300)
plt.close()

plt.figure(figsize=(30, 15))
plt.plot(showAngle['Time'], showAngle['Zen'], label='Elevation', color='red', marker='x', linestyle='--')
plt.xlabel('Time')
plt.ylabel('Angle (degrees)')
plt.title('Zen over Time')
plt.grid()
plt.legend()
plt.xticks(rotation=30)
plt.savefig('Plots/Zen_over_Time.png',dpi = 300)
plt.close()

plt.figure(figsize=(30, 15))
plt.hist(showAngle['AZ'], bins=100, color='blue', alpha=0.7, edgecolor='white')
plt.xlabel('Angle (degrees)')
plt.ylabel('Number of Occurrences')
plt.title('Histogram of AZ')
plt.grid()
plt.savefig('Plots/Histogram_AZ.png',dpi = 300)
plt.close()

plt.figure(figsize=(30, 15))
plt.hist(showAngle['Zen'], bins=100, color='red', alpha=0.7, edgecolor='white')
plt.xlabel('Angle (degrees)')
plt.ylabel('Number of Occurrences')
plt.title('Histogram of Zen')
plt.grid()
plt.savefig('Plots/Histogram_Zen.png',dpi = 300)
plt.close()

plt.figure(figsize=(30, 15))
plt.plot(showTSRC['T_mid'], showTSRC['T0_ave'], label='T0 Average', color='tab:blue', marker='o', linestyle='-')
plt.xlabel('Time')
plt.ylabel('Temperature (K)')
plt.title('T0 over Time')
plt.grid()
plt.legend()
plt.xticks(rotation=30)
plt.savefig('Plots/T0_over_Time.png',dpi = 300)
plt.close()

plt.figure(figsize=(30, 15))
plt.plot(showTSRC['T_mid'], showTSRC['T1_ave'], label='T1 Average', color='tab:orange', marker='x', linestyle='--')
plt.xlabel('Time')
plt.ylabel('Temperature (K)')
plt.title('T1 over Time')
plt.grid()
plt.legend()
plt.xticks(rotation=30)
plt.savefig('Plots/T1_over_Time.png',dpi = 300)
plt.close()

plt.figure(figsize=(30, 15))
plt.plot(showTSRC['T_mid'], showTSRC['T2_ave'], label='T2 Average', color='tab:green', marker='o', linestyle='-')
plt.xlabel('Time')
plt.ylabel('Temperature (K)')
plt.title('T2 over Time')
plt.grid()
plt.legend()
plt.xticks(rotation=30)
plt.savefig('Plots/T2_over_Time.png',dpi = 300)
plt.close()

plt.figure(figsize=(30, 15))
plt.plot(showTSRC['T_mid'], showTSRC['T3_ave'], label='T3 Average', color='tab:red', marker='x', linestyle='--')
plt.xlabel('Time')
plt.ylabel('Temperature (K)')
plt.title('T3 over Time')
plt.grid()
plt.legend()
plt.xticks(rotation=30)
plt.savefig('Plots/T3_over_Time.png',dpi = 300)
plt.close()

plt.figure(figsize=(30, 15))
plt.hist(showTSRC['T0_ave'], bins=100, color='tab:blue', alpha=0.7, label='T0 Average', edgecolor='white')
plt.xlabel('Temperature (K)')
plt.ylabel('Number of Occurrences')
plt.title('Histogram of T0')
plt.grid()
plt.legend()
plt.savefig('Plots/Histogram_T0.png',dpi = 300)
plt.close()

plt.figure(figsize=(30, 15))
plt.hist(showTSRC['T1_ave'], bins=100, color='tab:orange', alpha=0.7, label='T1 Average', edgecolor='white')
plt.xlabel('Temperature (K)')
plt.ylabel('Number of Occurrences')
plt.title('Histogram of T1')
plt.grid()
plt.legend()
plt.savefig('Plots/Histogram_T1.png',dpi = 300)
plt.close()

plt.figure(figsize=(30, 15))
plt.hist(showTSRC['T2_ave'], bins=100, color='tab:green', alpha=0.7, label='T2 Average', edgecolor='white')
plt.xlabel('Temperature (K)')
plt.ylabel('Number of Occurrences')
plt.title('Histogram of T2')
plt.grid()
plt.legend()
plt.savefig('Plots/Histogram_T2.png',dpi = 300)
plt.close()

plt.figure(figsize=(30, 15))
plt.hist(showTSRC['T3_ave'], bins=100, color='tab:red', alpha=0.7, label='T3 Average', edgecolor='white')
plt.xlabel('Temperature (K)')
plt.ylabel('Number of Occurrences')
plt.title('Histogram of T3')
plt.grid()
plt.legend()
plt.savefig('Plots/Histogram_T3.png',dpi = 300)
plt.close()

end_time = perf_counter()
print(f"Plots done take {end_time - start_time}")

